version: '3'
services:
  app:
    container_name: breaking_app
    image: node:22
    environment:
      NODE_ENV: development
      DATABASE_URL: 'postgres://root:hunter2@breaking_db/breakingbot'
      HUBOT_LOG_LEVEL: '${HUBOT_LOG_LEVEL:-info}'
      JIRA_EMAIL: '${JIRA_EMAIL}'
      JIRA_API_TOKEN: '${JIRA_API_TOKEN}'
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      WPCOM_API_TOKEN: '${WPCOM_API_TOKEN}'
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: bash -c "npm install && npm run start:dev"
    depends_on:
      - db

  db:
    container_name: breaking_db
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: breakingbot
    volumes:
      - ./lib/data/schema/sql:/docker-entrypoint-initdb.d
